version: '3.8'

services:
  postgres-jwt:
    image: postgres:15.1
    container_name: pg-auth
    environment:
      - POSTGRES_DB=chat-auth
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    restart: always

  chat-jwt:
    container_name: chat-jwt
    depends_on:
      - postgres-jwt
    environment:
      - DB_URL=jdbc:postgresql://postgres-jwt:5432/chat-auth
      - DB_USERNAME=user
      - DB_PASSWORD=123
    build:
      context: .
      dockerfile: Dockerfile.jvm
    ports:
      - "8090:8090"